name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install latest npm
        run: |
          sudo npm install -g npm@
          npm config set update-notifier false
      - name: Authenticate with NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Semantic release
        if: success()
        continue-on-error: true
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
      - name: Clean up End-to-End test resources
        if: always()
        run: |
          node cli drop-athena-resources
          node cli purge-buckets
          npx cdk -a 'node dist/cdk/cloudformation-test.js' destroy -f '*'
          npx cdk -a 'node dist/cdk/cloudformation-sourcecode.js' destroy -f '*'
